const data = [
  
  {
    imageUrl: "./viewer/source/images/16.png",
    altText: "Banner Back-End Matrix",
    title: "Back-End Matrix",
    description: "Pixellers Studio",
    imageFileName: "16.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/24.png",
    altText: "Banner Wave",
    title: "Wave",
    description: "Biasiolo",
    imageFileName: "24.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/4.png",
    altText: "Banner Javascript",
    title: "Javascript",
    description: "Biasiolo",
    imageFileName: "4.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/31.png",
    altText: "Banner Design",
    title: "Design",
    description: "Pixellers Studio",
    imageFileName: "31.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/27.png",
    altText: "Banner Faith",
    title: "Faith",
    description: "Pixellers Studio",
    imageFileName: "25.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/41.png",
    altText: "Banner IA",
    title: "IA",
    description: "Pixellers Studio",
    imageFileName: "41.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/28.png",
    altText: "Banner Open to Work",
    title: "Open to Work",
    description: "Biasiolo",
    imageFileName: "28.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/39.png",
    altText: "Banner Spider",
    title: "Spider",
    description: "Biasiolo",
    imageFileName: "39.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/1.png",
    altText: "Banner Here Comes the Night",
    title: "Here Comes the Night",
    description: "Biasiolo",
    imageFileName: "1.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/38.png",
    altText: "Banner Terminals",
    title: "Terminals",
    description: "Biasiolo",
    imageFileName: "38.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/36.png",
    altText: "Banner Ice Cube",
    title: "Ice Cube",
    description: "Biasiolo",
    imageFileName: "36.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/40.png",
    altText: "Banner Dev",
    title: "Dev",
    description: "Pixellers Studio",
    imageFileName: "40.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/23.png",
    altText: "Banner Life is Good",
    title: "Life is Good",
    description: "Pixellers Studio",
    imageFileName: "23.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/42.png",
    altText: "Banner O'Clock",
    title: "O'Clock",
    description: "Biasiolo",
    imageFileName: "42.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/5.png",
    altText: "Banner Coding",
    title: "Coding",
    description: "Pixellers Studio",
    imageFileName: "5.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/6.png",
    altText: "Banner Techs",
    title: "Techs",
    description: "Biasiolo",
    imageFileName: "6.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/7.png",
    altText: "Banner Saturated Desktop",
    title: "Saturated Desktop",
    description: "Biasiolo",
    imageFileName: "7.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/8.png",
    altText: "Banner Water Fly",
    title: "Water Fly",
    description: "Pixellers Studio",
    imageFileName: "8.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/9.png",
    altText: "Banner Summer in the City",
    title: "Summer in the City",
    description: "Loving Spoonfull",
    imageFileName: "9.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/10.png",
    altText: "Banner The Black Hole",
    title: "The Black Hole",
    description: "Biasiolo",
    imageFileName: "10.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/2.png",
    altText: "Banner Neural",
    title: "Neural",
    description: "Pixellers Studio",
    imageFileName: "2.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/11.png",
    altText: "Banner Maggie May",
    title: "Maggie May",
    description: "R. Stewart",
    imageFileName: "11.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/13.png",
    altText: "Banner Flash",
    title: "Flash",
    description: "Biasiolo",
    imageFileName: "13.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/30.png",
    altText: "Banner B&W",
    title: "B&W",
    description: "Biasiolo",
    imageFileName: "30.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/19.png",
    altText: "Banner Bright Birds",
    title: "Bright Birds",
    description: "Biasiolo",
    imageFileName: "19.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/12.png",
    altText: "Banner Yellow Brick",
    title: "Yellow Brick",
    description: "João Elton",
    imageFileName: "12.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/14.png",
    altText: "Banner Upstairs",
    title: "Upstairs",
    description: "Pixellers Studio",
    imageFileName: "14.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/15.png",
    altText: "Banner Green Storm",
    title: "Green Storm",
    description: "Pixellers Studio",
    imageFileName: "15.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/3.png",
    altText: "Banner Sunday Morning",
    title: "Sunday Morning",
    description: "L. Reed",
    imageFileName: "3.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/37.png",
    altText: "Banner ETH",
    title: "ETH",
    description: "Pixellers Studio",
    imageFileName: "37.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/43.png",
    altText: "Banner Styles",
    title: "Styles",
    description: "Biasiolo",
    imageFileName: "43.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/17.png",
    altText: "Banner Cantarola",
    title: "Cantarola",
    description: "Pixellers Studio",
    imageFileName: "17.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/18.png",
    altText: "Banner Centurion",
    title: "Centurion",
    description: "Biasiolo",
    imageFileName: "18.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/20.png",
    altText: "Banner Transform",
    title: "Transform",
    description: "Biasiolo",
    imageFileName: "20.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/21.png",
    altText: "Banner Water World",
    title: "Water World",
    description: "Pixellers Studio",
    imageFileName: "21.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/22.png",
    altText: "Banner A Cidade",
    title: "A Cidade",
    description: "Biasiolo",
    imageFileName: "22.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/25.png",
    altText: "Banner Optical",
    title: "Optical",
    description: "Biasiolo",
    imageFileName: "25.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/26.png",
    altText: "Banner Hieróglifo",
    title: "Hieróglifo",
    description: "Pixellers Studio",
    imageFileName: "26.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/29.png",
    altText: "Banner On Space",
    title: "On Space",
    description: "Biasiolo",
    imageFileName: "29.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/32.png",
    altText: "Banner Orch",
    title: "Orch",
    description: "Pixellers Studio",
    imageFileName: "32.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/33.png",
    altText: "Banner Party On",
    title: "Party On",
    description: "Biasiolo",
    imageFileName: "33.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/34.png",
    altText: "Banner Palm Trees",
    title: "Palm Trees",
    description: "Biasiolo",
    imageFileName: "34.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/35.png",
    altText: "Banner x",
    title: "X",
    description: "Biasiolo",
    imageFileName: "35.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/44.png",
    altText: "Banner Game On",
    title: "Game On",
    description: "Pixellers Studio",
    imageFileName: "44.png",
    tags: "design",
  },
  {
    imageUrl: "./viewer/source/images/45.png",
    altText: "Banner ETH",
    title: "Magnifying Glass",
    description: "Pixellers Studio",
    imageFileName: "45.png",
    tags: "design",
  }
  

  //objetos para cada banner
];

export default data;